version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: secure_storage_postgres
    environment:
      POSTGRES_DB: secure_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - secure_storage_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d secure_storage"]
      interval: 5s
      timeout: 5s
      retries: 10

  control_server:
    build:
      context: ./control_server
    container_name: secure_storage_control
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/secure_storage
      JWT_SECRET: supersecretkey
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - secure_storage_net
    volumes:
      - ./control_server:/app

  storage_node_1:
    build:
      context: ./storage_node
    container_name: storage_node_1
    environment:
      NODE_ID: node-1
      NODE_NAME: storage-node-1
      NODE_REGION: india
      STORAGE_PATH: /data/node_storage
      CONTROL_SERVER_URL: http://control_server:8000
    ports:
      - "8001:8000"
    networks:
      - secure_storage_net
    volumes:
      - storage_node_1_data:/data/node_storage
      - ./storage_node:/app

  storage_node_2:
    build:
      context: ./storage_node
    container_name: storage_node_2
    environment:
      NODE_ID: node-2
      NODE_NAME: storage-node-2
      NODE_REGION: eu
      STORAGE_PATH: /data/node_storage
      CONTROL_SERVER_URL: http://control_server:8000
    ports:
      - "8002:8000"
    networks:
      - secure_storage_net
    volumes:
      - storage_node_2_data:/data/node_storage
      - ./storage_node:/app

  storage_node_3:
    build:
      context: ./storage_node
    container_name: storage_node_3
    environment:
      NODE_ID: node-3
      NODE_NAME: storage-node-3
      NODE_REGION: us
      STORAGE_PATH: /data/node_storage
      CONTROL_SERVER_URL: http://control_server:8000
    ports:
      - "8003:8000"
    networks:
      - secure_storage_net
    volumes:
      - storage_node_3_data:/data/node_storage
      - ./storage_node:/app

volumes:
  postgres_data:
  storage_node_1_data:
  storage_node_2_data:
  storage_node_3_data:

networks:
  secure_storage_net:
    driver: bridge
