services:

  gateway:
    build: 
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    environment:
      - REGION_POLICY=EU
    ports:
      - "8000:8000"
    depends_on:
      - node1
      - node2
      - node3

  node1:
    build:
      context: .
      dockerfile: node/Dockerfile
    container_name: node1
    environment:
      - NODE_ID=node1
      - PORT=5001
      - REGION=IN
    ports:
      - "5001:5001"
    volumes:
      - ./data/node1:/app/data/node1

  node2:
    build:
      context: .
      dockerfile: node/Dockerfile
    container_name: node2
    environment:
      - NODE_ID=node2
      - PORT=5002
      - REGION=EU
    ports:
      - "5002:5002"
    volumes:
      - ./data/node2:/app/data/node2

  node3:
    build:
      context: .
      dockerfile: node/Dockerfile
    container_name: node3
    environment:
      - NODE_ID=node3
      - PORT=5003
      - REGION=IN
    ports:
      - "5003:5003"
    volumes:
      - ./data/node3:/app/data/node3